---
title: "C9W2 Assignment"
author: "Nicholas Neo"
date: "13 July 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview
Create a webpage using R Markdown that features a map created with Leaflet

### *Map of some famous Chicken Rice Stalls in Singapore for tourists*
[Source](https://www.womensweekly.com.sg/gallery/family/best-chicken-rice-stalls-we-love-in-singapore/)
```{r}
library(leaflet)
coords <- data.frame(lat = c(1.299950, 1.303940, 1.343340, 1.313170, 1.320520, 1.307180, 1.307200, 1.348290),
           lng = c(103.840200, 103.901350, 103.775140, 103.785640, 103.742630, 103.833810, 103.906420, 103.853170))
popup <- c("Jew Kit Hainanese Chicken Rice", "Boneless Chicken Rice Katong Shopping Centre", "Boon Tong Kee Chicken Rice", "Tong Fong Fatt Hainanese Boneless Chicken Rice", "Poh Poh Roasted Chicken Rice", "Hainanese Delicacy", "Five Star Hainanese Chicken Rice", "Ming Kee Chicken Rice")
coords %>% 
    leaflet() %>%
    addTiles() %>%
    addMarkers(popup = popup)
```

